image: Visual Studio 2015

platform: x64

configuration: Release

build:
  parallel: true

before_build:
  - choco install opencv
  - dir c:\tools\opencv\build\x64
  - git submodule update --init --recursive

build_script:
  - cmake -H. -Bbuild -DIMAGESTEGO_COMPRESSION_SUPPORT=ON -DIMAGESTEGO_BUILD_TESTS=ON -DIMAGESTEGO_BUILD_EXAMPLES=ON 
    -DOpenCV_DIR=c:\tools\opencv\build\x64\vc14
  - cmake --build build
  - cmake --build build --target test
