image: Visual Studio 2015

platform:
  - x86
  - x64

configuration: Release

build:
  parallel: true

before_build:
  - choco upgrade chocolatey
  - choco install opencv -y
  - refreshenv

build_script:
  - cmake -H. -Bbuild -DIMAGESTEGO_COMPRESSION_SUPPORT=ON -DIMAGESTEGO_BUILD_TESTS=ON -DIMAGESTEGO_BUILD_EXAMPLES=ON
  - cmake --build build
  - cmake --build build --target test
