image: Visual Studio 2019

platform: x64

branches:
  except:
    - ci/actions

configuration: Release

install:
  - curl -fsSL -o opencv.zip https://github.com/opencv/opencv/releases/download/4.5.0/opencv-4.5.0-dldt-2021.1-vc16-avx2.zip
  - 7z x opencv.zip
  - opencv\build\setup_vars_opencv4.cmd
  - git submodule update --init --recursive

environment:
  OPENCV_DIR: $(APPVEYOR_BUILD_FOLDER)\opencv\build

before_build:
  - cmake -B test -G "Visual Studio 16 2019" -A x64 -D IMAGESTEGO_BUILD_TESTS=ON -D CMAKE_BUILD_TYPE=Release .

build:
  parallel: true
  project: $(APPVEYOR_BUILD_FOLDER)\test\$(APPVEYOR_PROJECT_NAME).sln

test_script:
  - cd test
  - ctest -C Release --verbose
  - cd ..

after_test:
  - cmake -B test -D CPACK_GENERATOR=WIX -D CMAKE_BUILD_TYPE=Release .
  - cmake --build test --config Release --target package

artifacts:
  - path: test\*.msi
    name: 'imagestego package'

deploy:
  provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: 'imagestego release'
  auth_token:
    secure: xQBekBmkWo2ATAVUhWEGN+ji3rI78/lHWv8BcnVAe7DmZCI2PMRpKboMpnwQgwzM
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
