image: Visual Studio 2017

platform: x64

configuration: Release

build:
  parallel: true

cache:
  - c:\.hunter\
  - c:\tools\opencv\

before_build:
  # - git clone https://github.com/opencv/opencv.git
  # - git clone https://github.com/opencv/opencv_contrib.git
  # - cd opencv
  # - mkdir build
  # - cmake -H. -Bbuild -DBUILD_LIST=core,imgcodecs -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=OFF -DBUILD_opencv_apps=OFF -DCMAKE_INSTALL_PREFIX=install -DBUILD_TESTS=OFF -DBUILD_SHARED_LIBS=ON
  # - cmake --build build --config Release
  # - cmake --build build --target install --config Release
  # - cd ..
  - git submodule update --init --recursive
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

build_script:
  - cmake -H. -Bbuild -G "Visual Studio 15 2017" -A "x64" -DIMAGESTEGO_BUILD_TESTS=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DIMAGESTEGO_MODULES=core,comp
  - cmake --build build --config Release
  - cd build
  - ctest --verbose -C Release
