image: Visual Studio 2015

platform: x64

configuration: Release

build:
  parallel: true

before_build:
  - choco install opencv
  - git submodule update --init --recursive
  - setx -m OPENCV_DIR c:\tools\opencv\build\x64\vc14
  - setx -m PATH "$ENV:PATH;c:\tools\opencv\build\x64\vc14\bin"
  - refreshenv

build_script:
  - cmake -H. -Bbuild -DIMAGESTEGO_COMPRESSION_SUPPORT=ON -DIMAGESTEGO_BUILD_TESTS=ON -DIMAGESTEGO_BUILD_EXAMPLES=ON -DIMAGESTEGO_JPEG_SUPPORT=ON -DIMAGESTEGO_LOSSLESS_FORMATS=ON -DIMAGESTEGO_WITH_LIBJPEG=ON -DBUILD_SHARED_LIBS=ON -DOpenCV_DIR=%OPENCV_DIR%\lib
  - cmake --build build
  - cmake --build build --target test
