image: Visual Studio 2015

platform: x64

configuration: Release

build:
  parallel: true

cache:
  - c:\.hunter\
  - c:\tools\opencv\

before_build:
  - git clone https://github.com/opencv/opencv.git
  - git clone https://github.com/opencv/opencv_contrib.git
  - cd opencv
  - mkdir build
  - cmake -H. -Bbuild -DBUILD_LIST=core,imgcodecs -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=OFF -DBUILD_opencv_apps=OFF -DCMAKE_INSTALL_PREFIX=install -DBUILD_TESTS=OFF -DBUILD_SHARED_LIBS=ON
  - cmake --build build --config Release
  - cmake --build build --target install --config Release
  - cd ..
  - git submodule update --init --recursive

build_script:
  - cmake -H. -Bbuild -DIMAGESTEGO_BUILD_TESTS=ON -DIMAGESTEGO_WITH_LIBJPEG=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DOpenCV_DIR=opencv/install
  - cmake --build build --config Release
  - cd build
  - ctest --verbose -C Release
