image: Visual Studio 2017

platform: x64

configuration: Release

install:
  - git submodule update --init --recursive
  - git clone https://github.com/opencv/opencv.git
  - cd opencv
  - mkdir build
  - cmake -H. -Bbuild -A x64 -DBUILD_LIST=core,imgcodecs -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=OFF -DBUILD_opencv_apps=OFF -DCMAKE_INSTALL_PREFIX=$(APPVEYOR_BUILD_FOLDER) -DBUILD_TESTS=OFF -DBUILD_SHARED_LIBS=ON
  - cmake --build build --config Release -j 4
  - cmake --build build --target install --config Release
  - cd ..

before_build:
  - cmake -G "Visual Studio 15 2017" -A x64 -D IMAGESTEGO_BUILD_TESTS=ON -D IMAGESTEGO_MODULES=core,comp .

build:
  parallel: true
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln

test_script:
  - ctest -C Release --verbose
