language: cpp

# TODO: add more compilers
stages:
  - compile
  - test

jobs:
  include:
    - name: "GCC x86"
      stage: compile
      arch: amd64
      os: linux
      dist: bionic
      compiler: gcc
      env:
        - MODULES="core,lossless,comp,wavelet" COVERAGE=1
      addons:
        apt:
          packages:
            - lcov
    - name: "GCC-9 arm64"
      arch: arm64
      os: linux
      dist: bionic
      compiler: gcc-9
      env:
        - MODULES="core,lossless,comp,wavelet" CC=gcc-9 CXX=g++-9
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - gcc-9
            - g++-9
    - name: "Clang x86"
      arch: amd64
      os: linux
      dist: bionic
      compiler: clang
      env:
        - MODULES="core,lossless,comp,wavelet"
    - name: "GCC-9 x86"
      arch: amd64
      os: linux
      dist: bionic
      compiler: gcc-9
      env:
        - MODULES="core,lossless,comp,wavelet" CC=gcc-9 CXX=g++-9
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - gcc-9
            - g++-9
    - name: "Clang-10 arm64"
      arch: arm64
      os: linux
      dist: bionic
      compiler: clang-10
      env:
        - MODULES="core,lossless,comp,wavelet" CC=clang-10 CXX=clang++-10
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - clang-10
            - clang++-10
            - lld-10
    - name: "Apple Clang x86"
      os: osx
      compiler: clang
      env:
        - MODULES="core,lossless,comp,wavelet"
    - stage: test
      name: "Unit Tests"
      script:
        - cd $TRAVIS_BUILD_DIR
        - cp test/test.jpg build/
        - cd build
        - ctest --verbose

cache:
  directories:
    - $TRAVIS_BUILD_DIR/opencv

install: scripts/install-deps.sh

script: scripts/build.sh

after_script: scripts/coverage.sh
