language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - cmake-data
      - cmake
      - git
      - lcov

sudo: required

# install:
  # - git clone https://github.com/opencv/opencv.git
  # - git clone https://github.com/opencv/opencv_contrib.git
  # - cd opencv
  # - mkdir build
  # - cd build
  # - cmake -D BUILD_LIST=core,imgcodecs -D CMAKE_BUILD_TYPE=RELEASE -D BUILD_EXAMPLES=OFF -D BUILD_opencv_apps=OFF -D BUILD_DOCS=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_TESTS=OFF -D CMAKE_INSTALL_PREFIX=/usr/local/ ..
  # - make -j$(nproc)
  # - sudo make install
  # - cd ../../

# before_install:
  # - pip install --user cpp-coveralls

script:
  - mkdir -p build/ && cd build/
  - cmake -DIMAGESTEGO_BUILD_TESTS=ON -DBUILD_SHARED_LIBS=ON -DIMAGESTEGO_COVERAGE=ON -DCMAKE_BUILD_TYPE=Release -DIMAGESTEGO_MODULES=core,comp ..
  - make -j$(nproc)
  - ctest --verbose
  - cd ..

after_success:
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' "$(pwd)"'/third_party/*' --output-file coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
