language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

arch:
  - amd64
  - arm64

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - cmake-data
      - cmake
      - lcov

install: scripts/install-deps.sh

env:
  - MODULES="core,lossless,comp,wavelet"
  - MODULES="core,lossless,comp"

jobs:
  exclude:
    - os: linux
      env: MODULES="core,lossless,comp"
    - os: osx
      env: MODULES="core,lossless,comp,wavelet"
    - arch: arm64
      compiler: clang

cache:
  directories:
    - $TRAVIS_BUILD_DIR/opencv

script: scripts/build.sh

after_success:
  - cd build
  - cp ../test/test.jpg .
  - ctest --verbose
  - cd ..

after_script: scripts/coverage.sh
