language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - cmake-data
      - cmake
      - git
      - lcov

sudo: required

install:
  - if ! [ -d $TRAVIS_BUILD_DIR/opencv ]; then scripts/install-deps.sh; fi

script: scripts/build.sh

after_success:
  - cd build
  - cp ../test/test.jpg .
  - ctest --verbose
  - cd ..

after_script: scripts/coverage.sh
