language: cpp

# os:
  # - linux
  # - osx

# dist: bionic

# compiler:
  # - gcc
  # - clang

# arch:
  # - amd64
  # - arm64

# addons:
  # apt:
    # sources:
      # - sourceline: 'ppa:ubuntu-toolchain-r/test'
    # packages:
      # - cmake-data
      # - cmake
      # - lcov

# install: scripts/install-deps.sh

# env:
  # - MODULES="core,lossless,comp,wavelet"
  # - MODULES="core,lossless,comp"

jobs:
  include:
    - name: "gcc x86"
      arch: amd64
      os: linux
      dist: bionic
      compiler: gcc
      env:
        - MODULES="core,lossless,comp,wavelet"
    - name: "gcc armv8"
      arch: arm64
      os: linux
      dist: bionic
      compiler: gcc-9
      env:
        - MODULES="core,lossless,comp,wavelet" CC=gcc-9 CXX=g++-9
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - gcc-9
            - g++-9

    # - arch: arm64
      # compiler: gcc
      # addons:
        # apt:
          # sources:
            # - sourceline: 'ppa:ubuntu-toolchain-r/test'
          # packages:
            # - gcc-9
            # - g++-9

cache:
  directories:
    - $TRAVIS_BUILD_DIR/opencv

script: scripts/build.sh

after_success:
  - cd build
  - cp ../test/test.jpg .
  - ctest --verbose
  - cd ..

after_script: scripts/coverage.sh
