os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - cmake-data
      - cmake
      - git

language: cpp

sudo: required

# install:
  # - git clone https://github.com/opencv/opencv.git
  # - git clone https://github.com/opencv/opencv_contrib.git
  # - cd opencv
  # - mkdir build
  # - cd build
  # - cmake -D BUILD_LIST=core,imgcodecs -D CMAKE_BUILD_TYPE=RELEASE -D BUILD_EXAMPLES=OFF -D BUILD_opencv_apps=OFF -D BUILD_DOCS=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_TESTS=OFF -D CMAKE_INSTALL_PREFIX=/usr/local/ ..
  # - make -j$(nproc)
  # - sudo make install
  # - cd ../../

script:
  - mkdir -p build/ && cd build/
  - cmake -DIMAGESTEGO_BUILD_TESTS=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DIMAGESTEGO_MODULES=core,comp ..
  - make -j$(nproc)
  - ctest --verbose
