name: macOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: cmake
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Release -D IMAGESTEGO_BUILD_TESTS=ON -D IMAGESTEGO_BUILD_PERF_TESTS=OFF
      - name: build
        run: cmake --build build -j 10
      - name: test
      - name: test
        run: |
             cd build
             cp ../test/test.jpg .
             ctest -j 10 --output-on-failure
