name: Ubuntu

on: [push, pull_request]

jobs:
  gcc-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
             sudo apt update
             sudo apt install gcc-10 g++-10 libopencv-dev lcov
             git submodule update --init
      - name: cmake
        env:
          CC: gcc-10
          CXX: g++-10
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Debug -D IMAGESTEGO_BUILD_TESTS=ON -D IMAGESTEGO_BUILD_PERF_TESTS=OFF -D IMAGESTEGO_COVERAGE=ON
      - name: build
        run: cmake --build build -j 10
      - name: test
        run: |
             cd build
             cp ../test/test.jpg .
             ctest -j 10 --output-on-failure
             touch coverage.info
             lcov --remove coverage.info \
                '/usr/*' \
                "$(pwd)"'/third_party/*' \
                "$(pwd)"'/modules/core/third_party/*' \
                "$(pwd)"'/modules/core/test/*' \
                "$(pwd)"'/modules/compression/test/*' \
                "$(pwd)"'/modules/lossless/test/*' \
                --output-file coverage.info
             bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
  gcc-10-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
             sudo apt update
             sudo apt install gcc-10 g++-10 libopencv-dev
             git submodule update --init
      - name: cmake
        env:
          CC: gcc-10
          CXX: g++-10
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Release -D IMAGESTEGO_BUILD_TESTS=ON -D IMAGESTEGO_BUILD_PERF_TESTS=OFF
      - name: build
        run: cmake --build build -j 10
      - name: test
        run: |
             cd build
             cp ../test/test.jpg .
             ctest -j 10 --output-on-failure

  clang-10-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
             sudo apt update
             sudo apt install clang-10 libopencv-dev
             git submodule update --init
      - name: cmake
        env:
          CC: clang-10
          CXX: clang++-10
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Release -D IMAGESTEGO_BUILD_TESTS=ON -D IMAGESTEGO_BUILD_PERF_TESTS=OFF
      - name: build
        run: cmake --build build -j 10
      - name: test
        run: |
             cd build
             cp ../test/test.jpg .
             ctest -j 10 --output-on-failure
  gcc-9-arm64:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: uraimo/run-on-arch-action@v2.0.8
        with:
          arch: aarch64
          distro: ubuntu20.04
          githubToken: ${{ github.token }}
          install: |
               apt update -q -y
               apt install -q -y cmake gcc g++ git libopencv-dev
          run: |
               git clone https://github.com/shreddered/imagestego.git
               cd imagestego
               git checkout ${{ steps.extract_branch.outputs.branch }}
               git submodule update --init
               cmake -S . -B build -D CMAKE_BUILD_TYPE=Release -D IMAGESTEGO_BUILD_TESTS=ON -D IMAGESTEGO_BUILD_PERF_TESTS=OFF
               cmake --build build -j 10
               cd build
               cp ../test/test.jpg .
               ctest -j 10 --output-on-failure
