name: Ubuntu

on: [push, pull_request]

jobs:
  gcc_amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "install dependencies"
        run: |
             sudo apt update
             sudo apt install gcc-10 g++-10 libopencv-dev
      - name: build
        env:
          CC: gcc-10
          CXX: g++-10
        run: scripts/build.sh
      - name: test
        run: cd build; ctest -j 10 --output-on-failure

  clang_amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "install dependencies"
        run: |
             sudo apt update
             sudo apt install clang-10 libopencv-dev
      - name: build
        env:
          CC: clang-10
          CXX: clang++-10
        run: scripts/build.sh
      - name: test
        run: cd build; ctest -j 10 --output-on-failure
