name: Ubuntu

on: [push, pull_request]

jobs:
  gcc-10-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
             sudo apt update
             sudo apt install gcc-10 g++-10 libopencv-dev
             git submodule update --init
      - name: cmake
        env:
          CC: gcc-10
          CXX: g++-10
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Release -D IMAGESTEGO_BUILD_TEST=ON -D IMAGESTEGO_BUILD_PERF_TESTS=OFF
      - name: build
        run: cmake --build build -j 10
      - name: test
        run: |
             cd build
             cp ../test/test.jpg .
             ctest -j 10 --output-on-failure

  clang-10-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
             sudo apt update
             sudo apt install clang-10 libopencv-dev
             git submodule update --init
      - name: cmake
        env:
          CC: clang-10
          CXX: clang++-10
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Release -D IMAGESTEGO_BUILD_TEST=ON -D IMAGESTEGO_BUILD_PERF_TESTS=OFF
      - name: build
        run: cmake --build build -j 10
      - name: test
        run: |
             cd build
             cp ../test/test.jpg .
             ctest -j 10 --output-on-failure
